In [2]:
import numpy as np

Basic Array Creation

In [12]:
arr = np.array(["ff", "dd", "hi", 4.6, 1, 7])
arr

array(['ff', 'dd', 'hi', '4.6', '1', '7'], dtype='<U32')

In [14]:
np.array([2, 4.6, 3, 5])

array([2. , 4.6, 3. , 5. ])

In [15]:
np.array([1,2,56, 67, 5])

array([ 1,  2, 56, 67,  5])

In [18]:
l = [1,24,6]
l

[1, 24, 6]

In [19]:
a = np.array(l) # Vector
a

array([ 1, 24,  6])

In [20]:
l2 = [[1,2,4], [4,5,7]]
l2

[[1, 2, 4], [4, 5, 7]]

In [22]:
a2 = np.array(l2) # Matrix
a2

array([[1, 2, 4],
       [4, 5, 7]])

Array Generation Functions

In [23]:
np.arange(1,20,2) # Work as range() function

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.zeros(3) # for vector

array([0., 0., 0.])

In [26]:
np.zeros((3,3)) # for matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones(4) # for vector

array([1., 1., 1., 1.])

In [29]:
np.ones((4,6)) # for matrix

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
np.linspace(1,5,3) # Return evenly spaced numbers over a specified interval

array([1., 3., 5.])

In [31]:
np.linspace(1,5,13)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ,
       4.33333333, 4.66666667, 5.        ])

Random generation function

In [32]:
np.random.rand(5) # Normalization 0<= n <=1

array([0.47549104, 0.55009101, 0.89287154, 0.7628198 , 0.87426001])

In [36]:
np.random.randn(5) # Standardization -3<= n <=3

array([-1.97877573, -1.12287643,  0.34900328, -1.95398337, -0.84193518])

In [38]:
np.random.randint(5,10)

7

In [37]:
np.random.randint(5,10,3)

array([5, 9, 6])

Array attributes

In [16]:
arr2 = np.array([[8,2,3],[2,3,5],[5,6,7]])
arr2

array([[8, 2, 3],
       [2, 3, 5],
       [5, 6, 7]])

In [17]:
arr2.shape

(3, 3)

In [18]:
arr2.size

9

In [19]:
arr2.dtype

dtype('int64')

Array methods

In [20]:
arr2.min()

np.int64(2)

In [21]:
arr2.max()

np.int64(8)

In [22]:
arr2.sum()

np.int64(41)

In [29]:
arr2.mean()

np.float64(4.555555555555555)

In [23]:
np.sum(arr2, 0) # 0 mean column therefore it give summation of columns

array([15, 11, 15])

In [24]:
np.sum(arr2, 1) # 1 mean row therefore it give summation of rows

array([13, 10, 18])

In [30]:
arr2.argmax() # give index of max element if there are two max elements then it will give index of first element

np.int64(0)

In [32]:
arr2.argmin() # give index of min element if there are two min elements then it will give index of first element

np.int64(1)

Reshaping and Resizing

In [35]:
arr3 = np.arange(30)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
arr3.size

30

In [39]:
arr3.reshape(5,6) # rows x columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])