In [3]:
import numpy as np

Indexing and slicing of vectors

In [4]:
arr = np.arange(61,71)
arr

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70])

Indexing

In [8]:
arr[6]

np.int64(67)

Slicing

In [5]:
arr[2:7:2] # arr[start: stop-1: steps] => by default it is arr[0: len(arr): 1]

array([63, 65, 67])

In [8]:
arr[:7:]

array([61, 62, 63, 64, 65, 66, 67])

In [9]:
arr[7:]

array([68, 69, 70])

Indexing and slicing of matrix

In [20]:
arr2 = np.arange(61,81)
arr2

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80])

In [21]:
arr2.size

20

In [27]:
arr2 = arr2.reshape(5,4)
arr2

array([[61, 62, 63, 64],
       [65, 66, 67, 68],
       [69, 70, 71, 72],
       [73, 74, 75, 76],
       [77, 78, 79, 80]])

Indexing

In [31]:
arr2[2] # print row

array([69, 70, 71, 72])

In [30]:
arr2[0,0] 

np.int64(61)

Slicing

In [36]:
arr2[0:2,1:3] # arr[start: stop-1, start: stop-1] or arr[row_num, start:stop-1 ]

array([[62, 63],
       [66, 67]])

In [42]:
arr2[4, 2:] # or arr2[4:5, 2:4]

array([79, 80])

In [43]:
arr2[:, 2]  # slice columns

array([63, 67, 71, 75, 79])

Boolean Indexing

In [45]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
bool_index = arr3%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [55]:
arr4 = arr3[bool_index] # arr4 mai arr3 ke jo true values hai woh aajayenge 
arr4

array([ 2,  4,  6,  8, 10])