In [2]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operations

In [5]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

In [6]:
arr + arr2

array([ 8, 10, 12, 14, 16, 18])

In [7]:
arr - arr2

array([-6, -6, -6, -6, -6, -6])

In [8]:
arr * arr2

array([ 7, 16, 27, 40, 55, 72])

In [9]:
arr / arr2

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [10]:
arr // arr2

array([0, 0, 0, 0, 0, 0])

In [11]:
arr ** arr2

array([         1,        256,      19683,    1048576,   48828125,
       2176782336])

In [ ]:
# like this you can perform arithmetic operations on matrix also

Broadcasting

In [14]:
li = [1,2,3,4]
arr3 = np.array(li)

In [16]:
# In list for make every element +10 we have do loop but in array

In [18]:
arr3 = arr3 + 10
arr3

array([11, 12, 13, 14])

In [ ]:
# like this you can perform broadcasting on matrix also

Deep and Shallow copy

shallow copy

In [32]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a[4:6] *10 

array([50, 60])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
b = a.copy()
b[0] = 99 
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

deep copy

In [30]:
b= a
b[0] = 100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [31]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

Matrix operations


In [41]:
A = np.array([[1, 2], [3, 4], [3,6]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
# multiply

In [42]:
A @ B # or np.dot(A,B)

array([[19, 22],
       [43, 50],
       [57, 66]])

In [43]:
np.dot(A,B)

array([[19, 22],
       [43, 50],
       [57, 66]])

In [ ]:
# transpose

In [44]:
A.T

array([[1, 3, 3],
       [2, 4, 6]])

ADVANCE ARRAY MANIPULATION

Stacking of array

In [45]:
# You can't stack matrix

In [56]:
s1 = np.array([1, 2, 3, 4])
s2 = np.array([5, 6, 7, 8])

In [59]:
np.vstack((s1,s2)) # vertical (row) stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
np.hstack((s1,s2)) # horizontal (column) stacking

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
np.column_stack((s1,s2)) # take 1 ele from s1 abd 1 ele from s2 and make one row follwed by others

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [3]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.hsplit(c,2) 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [10]:
arr_split = np.vsplit(c,4)
arr_split

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [11]:
for i in arr_split:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
